name: tweet_scheduler

on: 
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.0.4'
    - run: julia -e bot/main.jl
      
      

