name: tweet_scheduler

on: 
  schedule:
    - cron: '*/2 * * * *'
      #runs every other minute (hopefully!)

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.0.4'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project src/memebot.jl 
      
      

