name: tweet_scheduler

on: 
  schedule:
    - cron: '0 12 * * sun'
      #Runs at 12:00 UTC on Sun (hopefully!)

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup ENV
      env:
        OAUTH_CONSUMER_KEY: "${{ secrets.OAUTH_CONSUMER_KEY}}"
        OAUTH_CONSUMER_SECRET: "${{ secrets.OAUTH_CONSUMER_SECRET}}"
        OAUTH_TOKEN: "${{ secrets.OAUTH_TOKEN}}"
        OAUTH_TOKEN_SECRET: "${{ secrets.OAUTH_TOKEN_SECRET}}"
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.0.4'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project src/memebot.jl 
      
      

